package tw.iii.qr.IndependentOrder.model.entity;
// default package
// Generated 2017/2/11 �U�� 08:19:25 by Hibernate Tools 4.0.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Guest generated by hbm2java
 */
@Entity
@Table(name = "guest")
public class Guest implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4608225981784227367L;
	private Integer id;
	private String guestId;
	private String name;
	private String company;
	private String platformAccount;
	private String email;
	private String country;
	private String tel;
	private String address;
	private String comment;
	private String phone;
	private String postcode;

	public Guest() {
	}

	public Guest(String guestId, String name, String company, String platformAccount, String email, String country,
			String tel, String address, String comment, String phone, String postcode) {
		this.guestId = guestId;
		this.name = name;
		this.company = company;
		this.platformAccount = platformAccount;
		this.email = email;
		this.country = country;
		this.tel = tel;
		this.address = address;
		this.comment = comment;
		this.phone = phone;
		this.postcode = postcode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "guestId", length = 45)
	public String getGuestId() {
		return this.guestId;
	}

	public void setGuestId(String guestId) {
		this.guestId = guestId;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "company", length = 100)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "platformAccount", length = 100)
	public String getPlatformAccount() {
		return this.platformAccount;
	}

	public void setPlatformAccount(String platformAccount) {
		this.platformAccount = platformAccount;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "country", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "tel", length = 45)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "comment", length = 1000)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "phone", length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "postcode", length = 50)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

}
