package tw.iii.qr.IndependentOrder.model.entity;
// default package
// Generated 2017/2/19 �U�� 10:31:38 by Hibernate Tools 4.0.0.Final

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StocktransferlogMaster generated by hbm2java
 */
@Entity
@Table(name = "stocktransferlog_master")
public class StockTransferlogMaster implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6088260069783020257L;
	private String stockTransferId;
	private Date date;
	private String staffName;
	private String stockStatus;
	private String newWarehouse;
	private String oldWarehouse;
	private String comment;

	public StockTransferlogMaster() {
	}

	public StockTransferlogMaster(String stockTransferId) {
		this.stockTransferId = stockTransferId;
	}

	public StockTransferlogMaster(String stockTransferId, Date date, String staffName, String stockStatus,
			String newWarehouse, String oldWarehouse, String comment) {
		this.stockTransferId = stockTransferId;
		this.date = date;
		this.staffName = staffName;
		this.stockStatus = stockStatus;
		this.newWarehouse = newWarehouse;
		this.oldWarehouse = oldWarehouse;
		this.comment = comment;
	}

	@Id

	@Column(name = "stockTransferId", unique = true, nullable = false, length = 50)
	public String getStockTransferId() {
		return this.stockTransferId;
	}

	public void setStockTransferId(String stockTransferId) {
		this.stockTransferId = stockTransferId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "staffName", length = 45)
	public String getStaffName() {
		return this.staffName;
	}

	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	@Column(name = "stockStatus", length = 45)
	public String getStockStatus() {
		return this.stockStatus;
	}

	public void setStockStatus(String stockStatus) {
		this.stockStatus = stockStatus;
	}

	@Column(name = "newWarehouse", length = 45)
	public String getNewWarehouse() {
		return this.newWarehouse;
	}

	public void setNewWarehouse(String newWarehouse) {
		this.newWarehouse = newWarehouse;
	}

	@Column(name = "oldWarehouse", length = 45)
	public String getOldWarehouse() {
		return this.oldWarehouse;
	}

	public void setOldWarehouse(String oldWarehouse) {
		this.oldWarehouse = oldWarehouse;
	}

	@Column(name = "comment", length = 45)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
