package tw.iii.qr.IndependentOrder.model.entity;
// default package
// Generated 2017/2/19 �U�� 02:17:27 by Hibernate Tools 4.0.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Storage generated by hbm2java
 */
@Entity
@Table(name = "storage")
public class Storage implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4265306598787709090L;
	private Integer item;
	private String sku;
	private String warehouse;
	private String warehousePosition1;
	private String warehousePosition2;
	private Integer qty;
	private String comment;
	private Date purchaseDate;
	private String company;

	public Storage() {
	}

	public Storage(String sku) {
		this.sku = sku;
	}

	public Storage(String sku, String warehouse, String warehousePosition1, String warehousePosition2, Integer qty,
			String comment, Date purchaseDate, String company) {
		this.sku = sku;
		this.warehouse = warehouse;
		this.warehousePosition1 = warehousePosition1;
		this.warehousePosition2 = warehousePosition2;
		this.qty = qty;
		this.comment = comment;
		this.purchaseDate = purchaseDate;
		this.company = company;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "item", unique = true, nullable = false)
	public Integer getItem() {
		return this.item;
	}

	public void setItem(Integer item) {
		this.item = item;
	}

	@Column(name = "SKU", nullable = false, length = 45)
	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	@Column(name = "warehouse", length = 100)
	public String getWarehouse() {
		return this.warehouse;
	}

	public void setWarehouse(String warehouse) {
		this.warehouse = warehouse;
	}

	@Column(name = "warehousePosition1", length = 45)
	public String getWarehousePosition1() {
		return this.warehousePosition1;
	}

	public void setWarehousePosition1(String warehousePosition1) {
		this.warehousePosition1 = warehousePosition1;
	}

	@Column(name = "warehousePosition2", length = 45)
	public String getWarehousePosition2() {
		return this.warehousePosition2;
	}

	public void setWarehousePosition2(String warehousePosition2) {
		this.warehousePosition2 = warehousePosition2;
	}

	@Column(name = "qty")
	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	@Column(name = "comment", length = 1000)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "purchaseDate", length = 19)
	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

}
