package tw.iii.qr.IndependentOrder.model.entity;
// default package
// Generated 2017/2/16 �W�� 08:02:48 by Hibernate Tools 4.0.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Warehouse generated by hbm2java
 */
@Entity
@Table(name = "warehouse")
public class Warehouse implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5574349661081505017L;
	private Integer id;
	private String warehouse;
	private String warehousename;

	public Warehouse() {
	}

	public Warehouse(String warehouse, String warehousename) {
		this.warehouse = warehouse;
		this.warehousename = warehousename;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "warehouse", length = 45)
	public String getWarehouse() {
		return this.warehouse;
	}

	public void setWarehouse(String warehouse) {
		this.warehouse = warehouse;
	}

	@Column(name = "warehousename", length = 45)
	public String getWarehousename() {
		return this.warehousename;
	}

	public void setWarehousename(String warehousename) {
		this.warehousename = warehousename;
	}

}
